version: '3.8'

services:
  tokopedia-scraper:
    build: .
    container_name: tokopedia_scraper
    restart: unless-stopped
    cpus: "2.0"
    mem_limit: 3.5g
    shm_size: 2g

    environment:
      - PYTHONUNBUFFERED=1
      - DISPLAY=:99
      - MAX_PAGES=10
      - SCRAPE_INTERVAL=3600
      - ANTI_SUSPEND_INTERVAL=300

    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./models:/app/models
      - /etc/localtime:/etc/localtime:ro

    ports:
      - "4000:4000"

    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 20s

    networks:
      - scraper-network

networks:
  scraper-network:
    driver: bridge
