parsing:
  tokopedia:
    product_card: "div.css-5wh65g"
    title: "span.+tnoqZhn89+NHUA43BpiJg=="
    price: "div.urMOIDHH7I0Iy1Dv2oFaNw=="
    shop: "span.si3CNdiG8AR0EaXvf6bFbQ=="
    rating: "span._2NfJxPu4JC-55aCJ8bEsyw=="
    review_count: "a[href*="/p/"]"
