base_scraper:
  products:
    product_item: ".product-item"
    product_name: ".product-name"
    product_price: ".product-price"

tokopedia_base:
  products:
    product_selectors:
      - 'div[class="css-5wh65g"]'
    name_selectors:
      - 'span[class="+tnoqZhn89+NHUA43BpiJg=="]'
    price_selectors:
      - 'div[class="urMOIDHH7I0Iy1Dv2oFaNw=="]'
    link_selector: 'a[href*="/p/"]'
    fallback_link_selector: 'a'
